### ISSUE TITLE
Falha ao compilar com -Werror

### ISSUE THREAD

**Issue by rafaelsierra** [LabProdam/ContadorDeCiclistas#1]
Devido ao uso do parametro `-Werror` o aplicativo não compila com o `make` resultando no seguinte stack trace:

<pre>
$ make
CCXX VideoOutput.cpp -o VideoOutput.o CFLAGS
VideoOutput.cpp: In member function ‘void VideoOutput::write(cv::Mat&)’:
VideoOutput.cpp:77:43: error: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
  ::write(this->fdrw, dst.data, FRAME_SIZE);
                                           ^
cc1plus: all warnings being treated as errors
make: *** [VideoOutput.o] Error 1
</pre>

Pode ser resolvido removendo o parametro `-Werror` do `Makefile`

**Comment by pnspinelli** [comment]
Não mais considerando warnings como erros para evitar o problema de compilação no futuro:

https://github.com/LabProdam/ContadorDeCiclistas/commit/143473b9ac4d61c628bd447fc4d62e5cf5732568
