### ISSUE TITLE
Erro de contagem

### ISSUE THREAD

**Issue by msilvalopes** [LabProdam/ContadorDeCiclistas#3]
Nessa hora: 10/04/2015 14:57:00 passaram dois ciclistas, mas como estavam muito perto ele contou apenas um.

**Comment by pnspinelli** [comment]
O contador é experimental. Problemas como esse são esperados. Melhorias futuras virão a eliminar esse tipo de inconveniente

**Comment by luiscape** [comment]
Close issue?
