### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [LabProdam/ContadorDeCiclistas#5]
I would like to point out that identifiers like "[`CAMERA__H`](https://github.com/LabProdam/ContadorDeCiclistas/blob/1752e0df52b60f1afee3c507b413878b37d59c1b/Camera.hpp#L1)" and "[`SENSORS__HPP`](https://github.com/LabProdam/ContadorDeCiclistas/blob/3540a559db579f5727100b3c8a196543d6ec9e21/Sensors.hpp#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by pnspinelli** [comment]
Thank you for pointing the issue up. Fixed on https://github.com/LabProdam/ContadorDeCiclistas/commit/f281f11cee1c4e9fdce56fc4d0ef9be0d9cb56e4

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/LabProdam/ContadorDeCiclistas/commit/f281f11cee1c4e9fdce56fc4d0ef9be0d9cb56e4).
