### ISSUE TITLE
Dados

### ISSUE THREAD

**Issue by admonteiro** [LabProdam/ContadorDeCiclistas#7]
Enquanto ainda não há um webservice para consultar os dados captados, como faço para ter acesso a eles? Desejo fazer uma análise das contagens feitas, como posso obter esses dados?

**Comment by pnspinelli** [comment]
Temporariamente estamos dispondo os dados obtidos em: https://github.com/LabProdam/DadosDaCiclovia

**Comment by admonteiro** [comment]
Obrigado!
