### ISSUE TITLE
Erro no make "libpthread.so.0: error adding symbols: DSO missing from command line"

### ISSUE THREAD

**Issue by gomex** [LabProdam/ContadorDeCiclistas#8]
# make

g++ CycloTracker.o VideoOutput.o ImageProcessor.o ObjectCounter.o ObjectLocator.o ObjectTracker.o PointTracker.o TrackedObject.o Sensors.o Camera.o CoordTransform.o Utils.o -o ./bin//CycloTracker -lm `pkg-config --libs opencv`
/usr/bin/ld: Sensors.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:46: recipe for target 'all' failed
make: **\* [all] Error 1

Estou usando Debian. Instalei tudo que era pré-requisito.

**Comment by bcarmo-caio** [comment]
Estava faltando a opção -lpthread para o ligador.
Obrigado por apontar o erro. Se mesmo assim não conseguir, avise por favor.
